version: "3.7"
services:
  web:
    build:
      context: php-apache/
    restart: always
    volumes:
      - ./html/:/var/www/html/
    ports:
      - "8088:80"
  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - ./mysql-data/.env
    volumes:
      - ./mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
